name: Puppeteer script for Later.com

on:
  workflow_dispatch:

jobs:

  build:

    env:
      # videourl: https://londonparkour.com/wp-content/uploads/2021/08/quick_test.mp4
      videofile: ldnpk_purple.png
      texturl: https://gist.githubusercontent.com/IORoot/dc4ce160c2d79fd7345c0b92c0ea820c/raw/b3bb3f87b9e4004b616082b3287d33c8a4631ba0/test.md
      textfile: test.md
            
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master


    - name: rclone download Media from GDrive
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: copy GDrive:${{ env.videofile }} ./${{ env.videofile }}


    - name: Download Gist Text
      run: |
        # wget ${{ env.videourl }}
        wget ${{ env.texturl }}
        ls -la
        cat ${{ env.videofile }}

