name: Puppeteer script for Later.com

on:
  workflow_dispatch:

jobs:

  build:

    env:
      # videourl: https://londonparkour.com/wp-content/uploads/2021/08/quick_test.mp4
      videofile: ldnpk_purple.png
      texturl: https://gist.githubusercontent.com/IORoot/dc4ce160c2d79fd7345c0b92c0ea820c/raw/b3bb3f87b9e4004b616082b3287d33c8a4631ba0/test.md
      textfile: test.md
      month: 8
      day: 23
      hour: 11
      minute: 00
      ampm: 'AM'
            
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master


    - name: rclone download Media from GDrive
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: copy GDrive:${{ env.videofile }} ./


    - name: Set media permissions
      run: |
        sudo chown runner:docker ${{ env.videofile }}
        ls -la


    - name: Download Gist Text and media permissions
      run: |
        wget ${{ env.texturl }}


    - name: Install
      uses: IORoot/action__puppeteer--media@master
      with:
        args: npm install


    - name: Test Code
      uses: IORoot/action__puppeteer--media@master
      with:
        args: node puppeteer.js ${{ secrets.LATER_USERNAME }} ${{ secrets.LATER_PASSWORD }} ${{ env.videofile }} ${{ env.textfile }} ${{ env.day }} ${{ env.month }} ${{ env.hour }} ${{ env.minute }} ${{ env.ampm }}


    - uses: actions/upload-artifact@v2
      with:
        name: upload screenshot
        path: ./screenshot*.png