name: Puppeteer script for Later.com

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set env
      run: echo "SCHEDULE=$(cat post_schedule.txt)" >> $GITHUB_ENV

      
    - name: Test Schedule
      run: echo ${{ env.SCHEDULE }}


    - name: rclone download Media from GDrive
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: copyurl --no-check-certificate $(cat post_videourl.txt) video.mp4


    - name: change owner
      run: |
        sudo chown runner:docker video.mp4
        ls -la


    - name: Install
      uses: IORoot/action__puppeteer--media@master
      with:
        args: npm install


    - name: Test Code
      uses: IORoot/action__puppeteer--media@master
      with:
        args: node puppeteer.js ${{ secrets.LATER_USERNAME }} ${{ secrets.LATER_PASSWORD }} video.mp4 post_text.txt ${{ env.SCHEDULE }}


    - uses: actions/upload-artifact@v2
      with:
        name: upload screenshot
        path: ./screenshot*.png