name: Puppeteer script for Later.com

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:

  build:

    env:
      remote: "https://londonparkour.com/wp-content/uploads/posts"
      videofile_location: "/Code/n8n/SocialPosts/video_post.mp4"


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Checkout social-media repo
      uses: actions/checkout@v2
      with:
        repository: IORoot/n8n__social-media
        path: posts

    - name: Download Text,Schedules and Video URL
      run: |
        mv ./posts/*.txt ./
        ls -la


    - name: Set env
      run: echo "SCHEDULE=$(cat ./posts/schedule.txt)" >> $GITHUB_ENV


    - name: rclone download Media from GDrive
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: copy GDrive:${{ env.videofile_location }} ./


    - name: change owner
      run: |
        sudo chown runner:docker video_post.mp4


    - name: Install
      uses: IORoot/action__puppeteer--media@master
      with:
        args: npm install


    - name: Test Code
      uses: IORoot/action__puppeteer--media@master
      with:
        args: node puppeteer.js ${{ secrets.LATER_USERNAME }} ${{ secrets.LATER_PASSWORD }} video_post.mp4 ${{ env.SCHEDULE }}


    - uses: actions/upload-artifact@v2
      with:
        name: upload screenshot
        path: ./screenshot*.png