name: Puppeteer script for Later.com

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:

  build:

    env:
      remote: "https://londonparkour.com/wp-content/uploads/posts"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    
    - name: Download Text,Schedules and Video URL
      run: |
        wget --no-check-certificate ${{ env.remote }}/post_text_fb.txt
        wget --no-check-certificate ${{ env.remote }}/post_text_ig.txt
        wget --no-check-certificate ${{ env.remote }}/post_text_tw.txt
        wget --no-check-certificate ${{ env.remote }}/post_schedule.txt
        wget --no-check-certificate ${{ env.remote }}/post_footer.txt
        wget --no-check-certificate ${{ env.remote }}/post_videourl.txt


    - name: Set env
      run: echo "SCHEDULE=$(cat post_schedule.txt)" >> $GITHUB_ENV


    - name: rclone download Media from GDrive
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: copyurl --no-check-certificate $(cat post_videourl.txt) video.mp4


    - name: change owner
      run: |
        sudo chown runner:docker video.mp4


    - name: Install
      uses: IORoot/action__puppeteer--media@master
      with:
        args: npm install


    - name: Test Code
      uses: IORoot/action__puppeteer--media@master
      with:
        args: node puppeteer.js ${{ secrets.LATER_USERNAME }} ${{ secrets.LATER_PASSWORD }} video.mp4 post_text.txt ${{ env.SCHEDULE }}


    - uses: actions/upload-artifact@v2
      with:
        name: upload screenshot
        path: ./screenshot*.png